// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSink creates a new instance of MockSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSink {
	mock := &MockSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSink is an autogenerated mock type for the Sink type
type MockSink struct {
	mock.Mock
}

type MockSink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSink) EXPECT() *MockSink_Expecter {
	return &MockSink_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockSink
func (_mock *MockSink) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSink_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockSink_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockSink_Expecter) Commit() *MockSink_Commit_Call {
	return &MockSink_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockSink_Commit_Call) Run(run func()) *MockSink_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSink_Commit_Call) Return(err error) *MockSink_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSink_Commit_Call) RunAndReturn(run func() error) *MockSink_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type MockSink
func (_mock *MockSink) ReadAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSink_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type MockSink_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *MockSink_Expecter) ReadAt(p any, off any) *MockSink_ReadAt_Call {
	return &MockSink_ReadAt_Call{Call: _e.mock.On("ReadAt", p, off)}
}

func (_c *MockSink_ReadAt_Call) Run(run func(p []byte, off int64)) *MockSink_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSink_ReadAt_Call) Return(n int, err error) *MockSink_ReadAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSink_ReadAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *MockSink_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockSink
func (_mock *MockSink) Size() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSink_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockSink_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockSink_Expecter) Size() *MockSink_Size_Call {
	return &MockSink_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockSink_Size_Call) Run(run func()) *MockSink_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSink_Size_Call) Return(n int64, err error) *MockSink_Size_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSink_Size_Call) RunAndReturn(run func() (int64, error)) *MockSink_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function for the type MockSink
func (_mock *MockSink) Truncate(size int64) error {
	ret := _mock.Called(size)

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSink_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type MockSink_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - size int64
func (_e *MockSink_Expecter) Truncate(size any) *MockSink_Truncate_Call {
	return &MockSink_Truncate_Call{Call: _e.mock.On("Truncate", size)}
}

func (_c *MockSink_Truncate_Call) Run(run func(size int64)) *MockSink_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSink_Truncate_Call) Return(err error) *MockSink_Truncate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSink_Truncate_Call) RunAndReturn(run func(size int64) error) *MockSink_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAt provides a mock function for the type MockSink
func (_mock *MockSink) WriteAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for WriteAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSink_WriteAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAt'
type MockSink_WriteAt_Call struct {
	*mock.Call
}

// WriteAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *MockSink_Expecter) WriteAt(p any, off any) *MockSink_WriteAt_Call {
	return &MockSink_WriteAt_Call{Call: _e.mock.On("WriteAt", p, off)}
}

func (_c *MockSink_WriteAt_Call) Run(run func(p []byte, off int64)) *MockSink_WriteAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSink_WriteAt_Call) Return(n int, err error) *MockSink_WriteAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSink_WriteAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *MockSink_WriteAt_Call {
	_c.Call.Return(run)
	return _c
}
