// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// ReadAt provides a mock function for the type MockSource
func (_mock *MockSource) ReadAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type MockSource_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *MockSource_Expecter) ReadAt(p any, off any) *MockSource_ReadAt_Call {
	return &MockSource_ReadAt_Call{Call: _e.mock.On("ReadAt", p, off)}
}

func (_c *MockSource_ReadAt_Call) Run(run func(p []byte, off int64)) *MockSource_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_ReadAt_Call) Return(n int, err error) *MockSource_ReadAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSource_ReadAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *MockSource_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockSource
func (_mock *MockSource) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockSource_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockSource_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockSource_Expecter) Size() *MockSource_Size_Call {
	return &MockSource_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockSource_Size_Call) Run(run func()) *MockSource_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Size_Call) Return(n int64) *MockSource_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockSource_Size_Call) RunAndReturn(run func() int64) *MockSource_Size_Call {
	_c.Call.Return(run)
	return _c
}
