// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/bigoci/internal/oci"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentials creates a new instance of MockCredentials. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentials(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentials {
	mock := &MockCredentials{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentials is an autogenerated mock type for the Credentials type
type MockCredentials struct {
	mock.Mock
}

type MockCredentials_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentials) EXPECT() *MockCredentials_Expecter {
	return &MockCredentials_Expecter{mock: &_m.Mock}
}

// Credential provides a mock function for the type MockCredentials
func (_mock *MockCredentials) Credential(ctx context.Context, registry oci.Registry) (oci.Credential, error) {
	ret := _mock.Called(ctx, registry)

	if len(ret) == 0 {
		panic("no return value specified for Credential")
	}

	var r0 oci.Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oci.Registry) (oci.Credential, error)); ok {
		return returnFunc(ctx, registry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oci.Registry) oci.Credential); ok {
		r0 = returnFunc(ctx, registry)
	} else {
		r0 = ret.Get(0).(oci.Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oci.Registry) error); ok {
		r1 = returnFunc(ctx, registry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentials_Credential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Credential'
type MockCredentials_Credential_Call struct {
	*mock.Call
}

// Credential is a helper method to define mock.On call
//   - ctx context.Context
//   - registry oci.Registry
func (_e *MockCredentials_Expecter) Credential(ctx any, registry any) *MockCredentials_Credential_Call {
	return &MockCredentials_Credential_Call{Call: _e.mock.On("Credential", ctx, registry)}
}

func (_c *MockCredentials_Credential_Call) Run(run func(ctx context.Context, registry oci.Registry)) *MockCredentials_Credential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 oci.Registry
		if args[1] != nil {
			arg1 = args[1].(oci.Registry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCredentials_Credential_Call) Return(credential oci.Credential, err error) *MockCredentials_Credential_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *MockCredentials_Credential_Call) RunAndReturn(run func(ctx context.Context, registry oci.Registry) (oci.Credential, error)) *MockCredentials_Credential_Call {
	_c.Call.Return(run)
	return _c
}
