// Package mocks holds the test double for the credential port the auth
// package implements: the oci package's Credentials.
//
// Every file here but this one is generated by mockery from
// internal/oci/credentials.go and must never be edited by hand. Regenerate
// them with `mise x -- mockery` after changing the port, and commit the
// result.
//
// Import it with an alias when a test also uses another adapter's mocks,
// since every one of those packages is named mocks.
package mocks
