// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/opencontainers/go-digest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobs creates a new instance of MockBlobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobs {
	mock := &MockBlobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobs is an autogenerated mock type for the Blobs type
type MockBlobs struct {
	mock.Mock
}

type MockBlobs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobs) EXPECT() *MockBlobs_Expecter {
	return &MockBlobs_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockBlobs
func (_mock *MockBlobs) Exists(ctx context.Context, dgst digest.Digest) (bool, error) {
	ret := _mock.Called(ctx, dgst)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest) (bool, error)); ok {
		return returnFunc(ctx, dgst)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest) bool); ok {
		r0 = returnFunc(ctx, dgst)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, digest.Digest) error); ok {
		r1 = returnFunc(ctx, dgst)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobs_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBlobs_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - dgst digest.Digest
func (_e *MockBlobs_Expecter) Exists(ctx any, dgst any) *MockBlobs_Exists_Call {
	return &MockBlobs_Exists_Call{Call: _e.mock.On("Exists", ctx, dgst)}
}

func (_c *MockBlobs_Exists_Call) Run(run func(ctx context.Context, dgst digest.Digest)) *MockBlobs_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobs_Exists_Call) Return(b bool, err error) *MockBlobs_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlobs_Exists_Call) RunAndReturn(run func(ctx context.Context, dgst digest.Digest) (bool, error)) *MockBlobs_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBlobs
func (_mock *MockBlobs) Get(ctx context.Context, dgst digest.Digest, off int64) (io.ReadCloser, int64, error) {
	ret := _mock.Called(ctx, dgst, off)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest, int64) (io.ReadCloser, int64, error)); ok {
		return returnFunc(ctx, dgst, off)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest, int64) io.ReadCloser); ok {
		r0 = returnFunc(ctx, dgst, off)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, digest.Digest, int64) int64); ok {
		r1 = returnFunc(ctx, dgst, off)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, digest.Digest, int64) error); ok {
		r2 = returnFunc(ctx, dgst, off)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBlobs_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlobs_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dgst digest.Digest
//   - off int64
func (_e *MockBlobs_Expecter) Get(ctx any, dgst any, off any) *MockBlobs_Get_Call {
	return &MockBlobs_Get_Call{Call: _e.mock.On("Get", ctx, dgst, off)}
}

func (_c *MockBlobs_Get_Call) Run(run func(ctx context.Context, dgst digest.Digest, off int64)) *MockBlobs_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlobs_Get_Call) Return(readCloser io.ReadCloser, n int64, err error) *MockBlobs_Get_Call {
	_c.Call.Return(readCloser, n, err)
	return _c
}

func (_c *MockBlobs_Get_Call) RunAndReturn(run func(ctx context.Context, dgst digest.Digest, off int64) (io.ReadCloser, int64, error)) *MockBlobs_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockBlobs
func (_mock *MockBlobs) Put(ctx context.Context, dgst digest.Digest, size int64, r io.Reader) error {
	ret := _mock.Called(ctx, dgst, size, r)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, digest.Digest, int64, io.Reader) error); ok {
		r0 = returnFunc(ctx, dgst, size, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlobs_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBlobs_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - dgst digest.Digest
//   - size int64
//   - r io.Reader
func (_e *MockBlobs_Expecter) Put(ctx any, dgst any, size any, r any) *MockBlobs_Put_Call {
	return &MockBlobs_Put_Call{Call: _e.mock.On("Put", ctx, dgst, size, r)}
}

func (_c *MockBlobs_Put_Call) Run(run func(ctx context.Context, dgst digest.Digest, size int64, r io.Reader)) *MockBlobs_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBlobs_Put_Call) Return(err error) *MockBlobs_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlobs_Put_Call) RunAndReturn(run func(ctx context.Context, dgst digest.Digest, size int64, r io.Reader) error) *MockBlobs_Put_Call {
	_c.Call.Return(run)
	return _c
}
