// Package mocks holds test doubles for the registry ports the oci package
// implements: the transfer package's Blobs and Manifests.
//
// Every file here but this one is generated by mockery from
// internal/transfer/ports.go and must never be edited by hand. Regenerate
// them with `mise x -- mockery` after changing a port, and commit the result.
//
// Import it with an alias when a test also uses the file adapter's mocks,
// since both packages are named mocks.
package mocks
