// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/opencontainers/go-digest"
	"github.com/opencontainers/image-spec/specs-go/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManifests creates a new instance of MockManifests. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifests(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifests {
	mock := &MockManifests{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManifests is an autogenerated mock type for the Manifests type
type MockManifests struct {
	mock.Mock
}

type MockManifests_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifests) EXPECT() *MockManifests_Expecter {
	return &MockManifests_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockManifests
func (_mock *MockManifests) Get(ctx context.Context) ([]byte, v1.Descriptor, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 v1.Descriptor
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, v1.Descriptor, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) v1.Descriptor); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(v1.Descriptor)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockManifests_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockManifests_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManifests_Expecter) Get(ctx any) *MockManifests_Get_Call {
	return &MockManifests_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockManifests_Get_Call) Run(run func(ctx context.Context)) *MockManifests_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManifests_Get_Call) Return(bytes []byte, descriptor v1.Descriptor, err error) *MockManifests_Get_Call {
	_c.Call.Return(bytes, descriptor, err)
	return _c
}

func (_c *MockManifests_Get_Call) RunAndReturn(run func(ctx context.Context) ([]byte, v1.Descriptor, error)) *MockManifests_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockManifests
func (_mock *MockManifests) Put(ctx context.Context, mediaType string, body []byte) (digest.Digest, error) {
	ret := _mock.Called(ctx, mediaType, body)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (digest.Digest, error)); ok {
		return returnFunc(ctx, mediaType, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) digest.Digest); ok {
		r0 = returnFunc(ctx, mediaType, body)
	} else {
		r0 = ret.Get(0).(digest.Digest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, mediaType, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifests_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockManifests_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaType string
//   - body []byte
func (_e *MockManifests_Expecter) Put(ctx any, mediaType any, body any) *MockManifests_Put_Call {
	return &MockManifests_Put_Call{Call: _e.mock.On("Put", ctx, mediaType, body)}
}

func (_c *MockManifests_Put_Call) Run(run func(ctx context.Context, mediaType string, body []byte)) *MockManifests_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManifests_Put_Call) Return(digest1 digest.Digest, err error) *MockManifests_Put_Call {
	_c.Call.Return(digest1, err)
	return _c
}

func (_c *MockManifests_Put_Call) RunAndReturn(run func(ctx context.Context, mediaType string, body []byte) (digest.Digest, error)) *MockManifests_Put_Call {
	_c.Call.Return(run)
	return _c
}
