package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"os"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

const (
	// kib is how many bytes one of the K and KiB units is.
	kib = 1 << 10
	// mib is how many bytes one of the M and MiB units is.
	mib = 1 << 20
	// gib is how many bytes one of the G and GiB units is.
	gib = 1 << 30
)

// Verification policies: how often a pulled file's content is re-hashed and
// compared against the fixture it was pushed from.
const (
	// verifyNone skips content verification on every iteration. Size is
	// still checked on every pull.
	verifyNone = "none"
	// verifyFirst verifies content on iteration zero only, which catches a
	// broken cell without paying the hash cost on every repeat.
	verifyFirst = "first"
	// verifyAll verifies content on every iteration.
	verifyAll = "all"
)

// Scenario names a spec may select. They are phases within one iteration,
// executed in this order, not independent matrix axes.
const (
	// scenarioColdPush times pushing a file the registry has never seen.
	scenarioColdPush = "cold-push"
	// scenarioWarmPush times re-pushing the same file to a second tag, which
	// exercises the per-part HEAD-skip path and nothing else.
	scenarioWarmPush = "warm-push"
	// scenarioColdPull times pulling the pushed artifact to a fresh path.
	scenarioColdPull = "cold-pull"
)

// Spec describes one benchmark run: which registries to talk to and the
// matrix of transfer shapes to measure against them.
//
// Sizes are strings in the spec file ("512MiB") and parsed on load; the
// grammar is the reference CLI's part-size grammar. The matrix is the full
// cross-product of targets, part sizes, worker counts, and file sizes, each
// cell repeated for the configured number of iterations.
type Spec struct {
	// RunID names the run. It becomes part of every repository path and
	// every fixture seed, so two runs with different IDs can never share
	// registry state or bytes.
	RunID string `json:"run_id"`

	// Targets are the registries the matrix runs against.
	Targets []Target `json:"targets"`

	// Scenarios picks which phases of each iteration are timed and
	// recorded. Order in the file does not matter; execution order is
	// always cold-push, warm-push, cold-pull.
	Scenarios []string `json:"scenarios"`

	// PartSizes are the part sizes to sweep, as size strings.
	PartSizes []string `json:"part_sizes"`

	// Workers are the worker counts to sweep.
	Workers []int `json:"workers"`

	// FileSizes are the transfer sizes to sweep, as size strings.
	FileSizes []string `json:"file_sizes"`

	// Iterations is how many times each cell repeats. Every iteration uses
	// freshly generated bytes, so a registry that deduplicates content can
	// never quietly turn a cold push into a no-op.
	Iterations int `json:"iterations"`

	// Verify is the content-verification policy: "none", "first", or
	// "all". Empty means "first".
	Verify string `json:"verify"`

	// FixtureDir is where fixture files and pull destinations are written.
	// Empty means the operating system's temporary directory. On a
	// benchmark box this should point at the fast disk.
	FixtureDir string `json:"fixture_dir,omitempty"`

	// partSizes holds PartSizes parsed to byte counts, in file order.
	partSizes []int64
	// fileSizes holds FileSizes parsed to byte counts, in file order.
	fileSizes []int64
}

// Target is one registry the matrix runs against.
type Target struct {
	// Name labels the target in cell IDs and result rows. It must be
	// unique within the spec.
	Name string `json:"name"`

	// Endpoint is the registry host or host:port. Spec files under version
	// control carry a placeholder; the -endpoint flag substitutes the real
	// address at run time so nobody edits JSON on a server.
	Endpoint string `json:"endpoint"`

	// PlainHTTP selects HTTP instead of HTTPS, which is how the local
	// benchmark registries are served.
	PlainHTTP bool `json:"plain_http,omitempty"`

	// RepoPrefix is the repository path prefix under the endpoint. The
	// run ID and cell ID are appended to it, giving every cell its own
	// repository.
	RepoPrefix string `json:"repo_prefix"`

	// AuthEnv names the environment-variable pair that holds this
	// target's credentials: <AuthEnv>_USERNAME and <AuthEnv>_TOKEN.
	// Empty means anonymous. Secrets never appear in spec files or argv.
	AuthEnv string `json:"auth_env,omitempty"`
}

// loadSpec reads, parses, and validates the spec file at path.
func loadSpec(path string) (*Spec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read spec: %w", err)
	}

	var spec Spec
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&spec); err != nil {
		return nil, fmt.Errorf("parse spec %s: %w", path, err)
	}

	if err := spec.validate(); err != nil {
		return nil, fmt.Errorf("spec %s: %w", path, err)
	}

	return &spec, nil
}

// validate checks the spec's shape and parses its size strings, so every
// later stage can trust the values it carries.
func (s *Spec) validate() error {
	if err := s.validateNames(); err != nil {
		return err
	}
	if err := s.validateTargets(); err != nil {
		return err
	}
	if err := s.validateMatrix(); err != nil {
		return err
	}

	return s.parseSizes()
}

// validateNames checks the run ID and the scenario and verify vocabulary.
func (s *Spec) validateNames() error {
	if !validPathSegment(s.RunID) {
		return fmt.Errorf("run_id %q: use lowercase letters, digits, dot, dash, and underscore", s.RunID)
	}

	if len(s.Scenarios) == 0 {
		return errors.New("scenarios is empty; list at least one of cold-push, warm-push, cold-pull")
	}
	for _, name := range s.Scenarios {
		switch name {
		case scenarioColdPush, scenarioWarmPush, scenarioColdPull:
		default:
			return fmt.Errorf("scenario %q: known scenarios are cold-push, warm-push, cold-pull", name)
		}
	}

	switch s.Verify {
	case "", verifyNone, verifyFirst, verifyAll:
	default:
		return fmt.Errorf("verify %q: use none, first, or all", s.Verify)
	}

	return nil
}

// validateTargets checks every target and the uniqueness of their names.
func (s *Spec) validateTargets() error {
	if len(s.Targets) == 0 {
		return errors.New("targets is empty; name at least one registry")
	}

	seen := make(map[string]bool, len(s.Targets))
	for _, target := range s.Targets {
		if !validPathSegment(target.Name) {
			return fmt.Errorf("target name %q: use lowercase letters, digits, dot, dash, and underscore", target.Name)
		}
		if seen[target.Name] {
			return fmt.Errorf("target name %q appears twice", target.Name)
		}
		seen[target.Name] = true

		if target.Endpoint == "" {
			return fmt.Errorf("target %q: endpoint is empty", target.Name)
		}
		if target.RepoPrefix == "" || target.RepoPrefix != strings.ToLower(target.RepoPrefix) {
			return fmt.Errorf("target %q: repo_prefix must be a non-empty lowercase repository path", target.Name)
		}
	}

	return nil
}

// validateMatrix checks the numeric axes.
func (s *Spec) validateMatrix() error {
	if len(s.PartSizes) == 0 || len(s.Workers) == 0 || len(s.FileSizes) == 0 {
		return errors.New("part_sizes, workers, and file_sizes must each list at least one value")
	}
	for _, count := range s.Workers {
		if count <= 0 {
			return fmt.Errorf("workers %d: must be positive", count)
		}
	}
	if s.Iterations <= 0 {
		return fmt.Errorf("iterations %d: must be positive", s.Iterations)
	}

	return nil
}

// parseSizes turns the spec's size strings into byte counts.
func (s *Spec) parseSizes() error {
	var err error
	if s.partSizes, err = parseSizeList("part_sizes", s.PartSizes); err != nil {
		return err
	}
	s.fileSizes, err = parseSizeList("file_sizes", s.FileSizes)

	return err
}

// verifyIteration reports whether the pulled content of iteration should be
// re-hashed and compared under the spec's verification policy.
func (s *Spec) verifyIteration(iteration int) bool {
	switch s.Verify {
	case verifyNone:
		return false
	case verifyAll:
		return true
	default:
		return iteration == 0
	}
}

// parseSizeList parses each size string in values, labeling errors with the
// spec field they came from.
func parseSizeList(field string, values []string) ([]int64, error) {
	sizes := make([]int64, 0, len(values))
	for _, value := range values {
		size, err := parseSize(value)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", field, err)
		}
		if slices.Contains(sizes, size) {
			return nil, fmt.Errorf("%s: %s appears twice", field, value)
		}
		sizes = append(sizes, size)
	}

	return sizes, nil
}

// validPathSegment reports whether text can serve as one segment of a
// repository path: non-empty, and only lowercase letters, digits, and the
// separators - _ . — the intersection of what registries accept.
func validPathSegment(text string) bool {
	if text == "" {
		return false
	}
	for _, r := range text {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= '0' && r <= '9':
		case r == '-' || r == '_' || r == '.':
		default:
			return false
		}
	}

	return true
}

// parseSize turns a size string into a byte count.
//
// The grammar is the reference CLI's: decimal digits, then an optional
// binary unit of B, K, KiB, M, MiB, G, or GiB, matched without regard to
// ASCII case. No spaces, no sign, no fraction, no decimal SI unit — a unit
// that quietly means something other than what the author thought would
// change what a cell measures.
func parseSize(text string) (int64, error) {
	if text == "" {
		return 0, errors.New("size is empty; write a byte count, or a size such as 512MiB")
	}
	if strings.ContainsFunc(text, unicode.IsSpace) {
		return 0, fmt.Errorf("size %q: spaces are not allowed; write the unit against the number", text)
	}
	if strings.ContainsAny(text, ".,") {
		return 0, fmt.Errorf(
			"size %q: fractions are not supported; write a whole number of a smaller unit (1.5MiB is 1536KiB)", text,
		)
	}

	digits, unit := splitSize(text)
	if digits == "" {
		return 0, fmt.Errorf("size %q: no digits; write a byte count, or a size such as 512MiB", text)
	}

	multiplier, err := unitMultiplier(text, unit)
	if err != nil {
		return 0, err
	}

	count, err := strconv.ParseUint(digits, 10, 63)
	if err != nil {
		return 0, fmt.Errorf("size %q: too large for a byte count", text)
	}
	if count == 0 {
		return 0, fmt.Errorf("size %q: must be positive", text)
	}
	if count > uint64(math.MaxInt64)/multiplier {
		return 0, fmt.Errorf("size %q: too large for a byte count", text)
	}

	//nolint:gosec // The multiply is bounded against MaxInt64 on the line above, so it fits.
	return int64(count * multiplier), nil
}

// formatSize renders size with the largest binary unit that divides it
// exactly, which is the shape a spec author would have typed. Cell IDs are
// built from this, so every positive size parses back to the same value.
func formatSize(size int64) string {
	switch {
	case size >= gib && size%gib == 0:
		return strconv.FormatInt(size/gib, 10) + "GiB"
	case size >= mib && size%mib == 0:
		return strconv.FormatInt(size/mib, 10) + "MiB"
	case size >= kib && size%kib == 0:
		return strconv.FormatInt(size/kib, 10) + "KiB"
	default:
		return strconv.FormatInt(size, 10) + "B"
	}
}

// splitSize cuts text at the end of its leading ASCII decimal digits and
// returns the digits and whatever followed them.
func splitSize(text string) (string, string) {
	end := 0
	for end < len(text) && text[end] >= '0' && text[end] <= '9' {
		end++
	}

	return text[:end], text[end:]
}

// unitMultiplier returns how many bytes one of unit is, or an error that
// teaches what to write instead.
func unitMultiplier(text, unit string) (uint64, error) {
	switch strings.ToLower(unit) {
	case "", "b":
		return 1, nil
	case "k", "kib":
		return kib, nil
	case "m", "mib":
		return mib, nil
	case "g", "gib":
		return gib, nil
	case "kb", "mb", "gb":
		return 0, fmt.Errorf(
			"size %q: decimal SI units are not supported; write the binary unit (KiB, MiB, GiB) or a plain byte count",
			text,
		)
	default:
		return 0, fmt.Errorf("size %q: unknown unit %q; use B, K or KiB, M or MiB, G or GiB", text, unit)
	}
}
