site_name: bigoci
site_description: Go library for uploading and downloading large files to and from OCI registries
site_url: https://componere.github.io/bigoci/
repo_name: componere/bigoci
repo_url: https://github.com/componere/bigoci
edit_uri: edit/master/docs/docs/
docs_dir: docs
site_dir: build
strict: true

theme:
  name: material
  language: en
  features:
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Explanation:
      - Design: explanation/design.md
  - Reference:
      - Format: reference/format.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/palette.css
